# Generated by Django 5.2.7 on 2025-10-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_type',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='message',
            field=models.TextField(default='Emergency! Please help me.'),
        ),
    ]
