# Generated by Django 5.2.7 on 2025-12-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_emergencyalert_alert_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyalert',
            old_name='location',
            new_name='location_text',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_emails',
            field=models.TextField(blank=True, help_text='Comma-separated emails for emergency contacts', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_telegram_chat_ids',
            field=models.TextField(blank=True, help_text='Comma-separated Telegram chat IDs to notify', null=True),
        ),
    ]
